export type AacWorkingGroupCohort = "secretariat" | "members" | "observers"

export type AacWorkingGroupMember = {
  name: string
  role: string
  organization: string
  cohort: AacWorkingGroupCohort
  bio?: string
  /** Portrait extracted from the Working Group PDF, when available */
  photo?: string
  /** Matched AAC partner logo, when the organisation already appears in the partners grid */
  logo?: string
  /** Reserved for organisation profile pages */
  profileHref?: string
}

export const AAC_WORKING_GROUP: AacWorkingGroupMember[] = [
  {
    name: "Zena Ali",
    role: "Partnerships Lead",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/zena-ali.jpg",
  },
  {
    name: "Keni Kariuki",
    role: "Co-Founder, Programs and Operations",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/keni-kariuki.jpg",
  },
  {
    name: "Joy Njeri",
    role: "Program Officer",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/joy-njeri.jpg",
  },
  {
    name: "Beatrice Njiiri",
    role: "Junior Research & Programs Officer",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/beatrice-njiiri.jpg",
  },
  {
    name: "Dennis Ndungu",
    role: "Community & Events Lead",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/dennis-ndungu.jpg",
  },
  {
    name: "Jackline Kamathi",
    role: "Senior Program Officer",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/jackline-kamathi.jpg",
  },
  {
    name: "Hildah Akwona",
    role: "Ecosystem Project Office",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/hildah-akwona-bw.jpg",
  },
  {
    name: "Phanice Kadzo",
    role: "Program Management Associate",
    organization: "Impact Hub Nairobi",
    cohort: "secretariat",
    photo: "/programs/aac/working-group/phanice-kadzo-bw.jpg",
  },
  {
    name: "Bruce Hiller",
    role: "Managing Partner",
    organization: "JBQ Africa",
    cohort: "members",
    photo: "/programs/aac/working-group/bruce-hiller.jpg",
    logo: "/programs/aac/partners/jbq-africa.png",
    bio: "More than 35 years in large- and small-scale farming, food processing, trading systems, and soft-commodity logistics across Africa. Former Regional Managing Director of BUNGE covering East Africa, and a Farm Africa Programme Advisory Committee member in the UK.",
  },
  {
    name: "Sylvia Kuria",
    role: "Founder & Director",
    organization: "Sylvia's Basket",
    cohort: "members",
    photo: "/programs/aac/working-group/sylvia-kuria.jpg",
    logo: "/programs/aac/partners/sylvias-basket.png",
    bio: "Smallholder organic farmer and entrepreneur who grew a 0.5-acre family farm into a 15-acre mixed organic operation. Through Sylvia's Basket she aggregates organic produce for bulk buyers and trains fellow farmers in agroecology and market access.",
  },
  {
    name: "Mwangi Murigi",
    role: "Founder & CEO",
    organization: "Nutrimzuri Farmcare",
    cohort: "members",
    photo: "/programs/aac/working-group/mwangi-murigi.jpg",
    logo: "/programs/aac/partners/nutrimzuri.png",
    bio: "Leads a circular-economy animal-feed enterprise using insects and single-cell proteins. Brings 8+ years in the animal-feeds industry and 5+ years running commercial-scale insect farms in East Africa.",
  },
  {
    name: "Heleen Verbeek",
    role: "Co-Founder",
    organization: "Green Intelligence Kenya",
    cohort: "members",
    photo: "/programs/aac/working-group/heleen-verbeek.jpg",
    logo: "/programs/aac/partners/green-intelligence.png",
    bio: "Regenerative agriculture and agroforestry specialist with six years' experience in landscape restoration and smallholder enterprise development. In 2025 Green Intelligence Kenya planted over 20,000 agroforestry trees with 200 farmers in Subukia and Tharaka Nithi.",
  },
  {
    name: "Geoffrey Ongoya Wafula",
    role: "Executive Director",
    organization: "IBMA Kenya",
    cohort: "members",
    photo: "/programs/aac/working-group/geoffrey-ongoya-wafula.jpg",
    logo: "/programs/aac/partners/ibma-kenya.png",
    bio: "Plant health and crop protection expert with over 16 years in nature-based solutions, project management, and regulatory affairs. Holds a Ph.D. in Plant Pathology and has worked across public and private organisations.",
  },
  {
    name: "Mildred Day",
    role: "Founder & CEO",
    organization: "Griincom Innovate",
    cohort: "members",
    photo: "/programs/aac/working-group/mildred-day.jpg",
    logo: "/programs/aac/partners/griincom.png",
    bio: "Leads a Nakuru social enterprise recycling 30–40 tons of organic waste a month into organic fertiliser, foliar feeds, and pest repellent. Founding board member of OFIMAK, the Organic Farm Inputs Manufacturers Association of Kenya.",
  },
  {
    name: "Sam Stewart",
    role: "Manager, Nature & Food",
    organization: "Systemiq",
    cohort: "members",
    photo: "/programs/aac/working-group/sam-stewart.jpg",
    logo: "/programs/aac/partners/systemiq.png",
    bio: "Over a decade designing regenerative land-use and nature-positive investment initiatives across Africa, including large-scale agroforestry and landscape restoration in coffee and cocoa value chains.",
  },
  {
    name: "Ebenezer Amadi",
    role: "Senior Program Manager",
    organization: "Bop Inc.",
    cohort: "members",
    photo: "/programs/aac/working-group/ebenezer-amadi.jpg",
    bio: "Strategic development leader across circular economy, climate action, and WASH. Has contributed to Kenya's Climate Change Act, Sustainable Waste Management Act, and Extended Producer Responsibility Regulations.",
  },
  {
    name: "Abigael Kosgey",
    role: "CEO and Co-Founder",
    organization: "Chemichemi Organics",
    cohort: "members",
    photo: "/programs/aac/working-group/abigael-kosgey.jpg",
    logo: "/programs/aac/partners/chemi-chemi-organic.png",
    bio: "Builds a circular-economy enterprise focused on soil regeneration through organic fertilisers, supporting smallholders to shift from chemical dependency to regenerative practices.",
  },
  {
    name: "Mary Mwema",
    role: "Ecosystem Development Director",
    organization: "DMTR Food",
    cohort: "members",
    photo: "/programs/aac/working-group/mary-mwema.jpg",
    bio: "Works on food-systems transformation for zero hunger, applying systems thinking to policy review, toolkit development, and partnerships for climate-smart, smallholder-inclusive interventions.",
  },
  {
    name: "Nagnouma Kone",
    role: "Manager, Africa Strategy & Partnerships",
    organization: "Global Green Growth Institute",
    cohort: "members",
    photo: "/programs/aac/working-group/nagnouma-kone.jpg",
    logo: "/programs/aac/partners/gggi.png",
    bio: "Head of GGGI's Kenya office, leading country programmes, partnerships, and alignment with national green-growth agendas. Expertise in climate policy and institutional partnerships across Africa.",
  },
  {
    name: "Millicent Okumu",
    role: "CEO and Co-Founder",
    organization: "Agriflex",
    cohort: "members",
    photo: "/programs/aac/working-group/millicent-okumu.jpg",
    logo: "/programs/aac/partners/agriflex.png",
    bio: "Leads a Kenyan agritech company advancing regenerative agriculture for smallholders and agrodealers. Integrates drones, digital tools, and mentorship to cut input costs and support climate-smart farming.",
  },
  {
    name: "Kajuju Kiogora",
    role: "Founder & CEO",
    organization: "Healthy Kajuju",
    cohort: "members",
    photo: "/programs/aac/working-group/kajuju-kiogora.jpg",
    bio: "Built Healthy Kajuju into a recognised Kenyan natural-foods brand of cereals, snacks, and related products, championing local manufacturing and making nutritious food more accessible.",
  },
  {
    name: "Ernest Chitechi",
    role: "Head of Corporate Affairs",
    organization: "Kenya Climate Innovation Center",
    cohort: "members",
    photo: "/programs/aac/working-group/ernest-chitechi.jpg",
    logo: "/programs/aac/partners/kcic.png",
    bio: "Results-driven executive with over 20 years leading strategy, reputation, and cross-functional teams. Holds an MBA in Strategic Management and currently heads Corporate Affairs at KCIC.",
  },
  {
    name: "Victoria Clause",
    role: "Agri-Food Consultant",
    organization: "Independent",
    cohort: "members",
    photo: "/programs/aac/working-group/victoria-clause.jpg",
    bio: "Agriculture, sustainability, and innovation professional with over 15 years in African markets, spanning smallholder and regenerative agriculture, clean energy, digital finance, and carbon.",
  },
  {
    name: "Monica Nderitu",
    role: "Regional Environment and Climate Change Advisor",
    organization: "Vi Agroforestry",
    cohort: "members",
    photo: "/programs/aac/working-group/monica-nderitu.jpg",
    logo: "/programs/aac/partners/vi-agroforestry.png",
    bio: "Provides technical expertise in climate resilience, sustainable land management, agroforestry, biodiversity, and livelihood enhancement for smallholder farmers. Researcher, consultant, and urban farmer.",
  },
  {
    name: "Virginia Wanjiku",
    role: "Youth Researcher",
    organization: "International Center for Research on Women",
    cohort: "members",
    photo: "/programs/aac/working-group/virginia-wanjiku.jpg",
    logo: "/programs/aac/partners/icrw.png",
    bio: "Research and development professional with a BSc in Agricultural Economics. Supports data-driven work across agriculture, gender, and health, translating findings into programme and policy insights.",
  },
  {
    name: "Moses Githua Kamau",
    role: "Advocate & Conservation Lead",
    organization: "Inspire Nature Consultancy",
    cohort: "members",
    photo: "/programs/aac/working-group/moses-githua-kamau.jpg",
    logo: "/programs/aac/partners/inspire-nature.png",
    bio: "Human-rights defender and conservation advocate with over 21 years across legal, governance, and NGO sectors. Advocate of the High Court of Kenya, focused on rights, civic education, and youth-centred conservation.",
  },
  {
    name: "Michael Barton",
    role: "Regenerative Agriculture & Soil Health Consultant",
    organization: "Independent",
    cohort: "members",
    photo: "/programs/aac/working-group/michael-barton.jpg",
    bio: "Soil biologist with 10 years on climate-resilient farming systems. Qualified Soil Food Web practitioner and permaculture designer, scaling composting systems and training farmers, NGOs, and policymakers.",
  },
  {
    name: "Jörn Fritzenkötter",
    role: "Head of Development",
    organization: "Democratic Society",
    cohort: "members",
    photo: "/programs/aac/working-group/jorn-fritzenkotter.jpg",
    bio: "Fundraiser and political scientist with a decade in international cooperation and democratic innovation. Co-leads fundraising and partnership strategy at Democratic Society; has worked with the Council of Europe, UN Women, and the ILO.",
  },
  {
    name: "Grace Kamere",
    role: "Head of Programs and Strategic Partnerships",
    organization: "Circle Innovation",
    cohort: "members",
    photo: "/programs/aac/working-group/grace-kamere.jpg",
    bio: "Youth development and social-innovation expert with over 10 years at the intersection of human-centred design and impact. Leads initiatives such as the Circularity Launchpad and has contributed to YALI and USAID Empowered Youth.",
  },
  {
    name: "John Kanja Muturi",
    role: "Extension Officer",
    organization: "County Government of Kiambu",
    cohort: "members",
    photo: "/programs/aac/working-group/john-kanja-muturi.jpg",
    bio: "Agricultural officer advancing regenerative farming through farm management, agronomy, and research. Has worked with icipe on pest management and managed operations at Grace Farm Orchards and Magana Farm.",
  },
  {
    name: "Sven Verwiel",
    role: "CEO & Co-Founder",
    organization: "Forest Foods",
    cohort: "members",
    photo: "/programs/aac/working-group/sven-verwiel.jpg",
    logo: "/programs/aac/partners/forest-foods.png",
    bio: "Regenerative systems entrepreneur bridging food, forestry, and enterprise. CEO of Forest Foods, Technical Director at LEAF Africa, and Managing Director of Tamalu Farm on Mount Kenya.",
  },
  {
    name: "Emily Addonizio",
    role: "Agriculture and Food Systems Expert",
    organization: "Independent",
    cohort: "members",
    photo: "/programs/aac/working-group/emily-addonizio.jpg",
    bio: "Thirteen-plus years leading climate-smart agriculture and resilience programmes across East Africa. Consults for UN agencies, NGOs, and private clients on programme design, M&E, and donor relations.",
  },
  {
    name: "Daan Vreeburg",
    role: "BD Manager, East Africa",
    organization: "Agriterra",
    cohort: "members",
    photo: "/programs/aac/working-group/daan-vreeburg.jpg",
    bio: "Ten years promoting private-sector development and agricultural cooperatives in Africa. Currently raising funds for a regenerative avocado and coffee farm, and moving into climate-solutions project management at Export Trading Group.",
  },
  {
    name: "Reuben Omega",
    role: "Agroecology Advisor",
    organization: "ShambaniPro Agri-Innovations",
    cohort: "members",
    photo: "/programs/aac/working-group/reuben-omega.jpg",
    bio: "Agricultural development professional with 8+ years in regenerative agriculture and smallholder empowerment. Also a research consultant with TechnoServe; holds an MSc in Agricultural and Applied Economics from the University of Nairobi.",
  },
  {
    name: "Alex Mwaura",
    role: "Country Director",
    organization: "Digital Green",
    cohort: "members",
    photo: "/programs/aac/working-group/alex-mwaura.jpg",
    logo: "/programs/aac/partners/digital-green.png",
    bio: "Two decades in humanitarian and development work. Leads Digital Green Kenya's FarmerChat AI advisory, reaching over 200,000 farmers, after 21 years running multi-sector resilience programmes across Africa.",
  },
  {
    name: "James Mureithi",
    role: "Managing Director",
    organization: "Key-Cert Services Limited",
    cohort: "members",
    photo: "/programs/aac/working-group/james-mureithi.jpg",
    bio: "Certification and agribusiness-compliance leader with 14+ years across Sub-Saharan Africa. Former Managing Director of Control Union Kenya; now advances market access and sustainability, and pilots a circular pineapple–goat farm in Kilifi.",
  },
  {
    name: "Miriam Wambui",
    role: "Programs Manager",
    organization: "Girls for Girls Kenya",
    cohort: "members",
    photo: "/programs/aac/working-group/miriam-wambui.jpg",
    bio: "Coordinates mentorship and leadership programmes for women, with nine years designing initiatives across East Africa. Launched the Malala Fund SisTech project in Africa and has partnered with the EU, Aga Khan Foundation, and Rutgers.",
  },
  {
    name: "Crispus Kinyua",
    role: "Executive Director",
    organization: "Institute for Food Justice and Development",
    cohort: "members",
    photo: "/programs/aac/working-group/crispus-kinyua.jpg",
    logo: "/programs/aac/partners/ifjad.png",
    bio: "Nutritionist and food-justice advocate. Founded Tofali Nutrition (Power Paste) and IFJAD to confront food injustice in Kenya, focusing on agroecology, consumer protection, and the right to safe, culturally meaningful food.",
  },
  {
    name: "Suhyeon Kang",
    role: "JPO, Program Development",
    organization: "Global Green Growth Institute",
    cohort: "members",
    photo: "/programs/aac/working-group/suhyeon-kang.jpg",
    logo: "/programs/aac/partners/gggi.png",
    bio: "Supports resource mobilisation and programme design at GGGI Kenya, including green hydrogen and circular-economy work. Previously managed KOICA programmes in Ghana and designed ecovillage projects with the Korea Green Fund.",
  },
  {
    name: "Sheena Raikundalia",
    role: "Chief Growth Officer",
    organization: "Kuza One",
    cohort: "members",
    photo: "/programs/aac/working-group/sheena-raikundalia.jpg",
    logo: "/programs/aac/partners/kuza.png",
    bio: "Sixteen-plus years across legal, financial services, and impact investment in Europe and Africa. Former Country Director of the UK–Kenya Tech Hub; UK-qualified solicitor with a law degree from Bristol and an MBA.",
  },
  {
    name: "Chuck Dennis Momanyi",
    role: "Manager, Urban–Rural Alliances (Food Systems) for Africa",
    organization: "C40 Cities",
    cohort: "members",
    photo: "/programs/aac/working-group/chuck-dennis-momanyi.jpg",
    bio: "Supports seven African cities to strengthen urban–rural food-system governance, institutional coordination, and regenerative SME and farmer programmes under the C40 Thriving Food Systems Accelerator.",
  },
  {
    name: "Njenga Muchekehu",
    role: "Deputy Regional Director for Africa",
    organization: "C40 Cities",
    cohort: "members",
    photo: "/programs/aac/working-group/njenga-muchekehu.jpg",
    bio: "Works with C40's Regional and Mayoral Engagement team to deepen relationships with African member cities, align with C40 Leadership Standards, and raise climate ambition across the continent.",
  },
  {
    name: "Esther Mwikali",
    role: "Network Executive",
    organization: "Small Foundation",
    cohort: "observers",
    photo: "/programs/aac/working-group/esther-mwikali.jpg",
    bio: "Grows and supports networks across Africa with a focus on systems change. Previously invested in early-stage companies at Renew Capital and led JICA's NINJA innovation programme at Growth Africa.",
  },
  {
    name: "Antony Wahome",
    role: "Head of Strategic Country Program Delivery",
    organization: "Mastercard Foundation",
    cohort: "observers",
    photo: "/programs/aac/working-group/antony-wahome.jpg",
    bio: "Market-systems, digital-economy, and MEL practitioner with over 14 years designing, implementing, and evaluating programmes with governments, development partners, and corporate foundations across sub-Saharan Africa.",
  },
  {
    name: "Khatuchi Khasandi",
    role: "Head of Corporate Affairs",
    organization: "Independent Consultant",
    cohort: "observers",
    photo: "/programs/aac/working-group/khatuchi-khasandi.jpg",
    bio: "Consults with the Lemelson Foundation and leads the Kenya Innovation Ecosystem Funders Forum. Previously directed invention-education partnerships at Rice360 and led ANDE's East Africa chapter.",
  },
  {
    name: "Wangari Ngunjiri",
    role: "Program Officer",
    organization: "Segal Family Foundation",
    cohort: "observers",
    photo: "/programs/aac/working-group/wangari-ngunjiri.jpg",
    bio: "Leads grantmaking and community-building for Kenya and Uganda partners. Holds a master's in Development Studies from Nelson Mandela University, with research rooted in feminist economic theory.",
  },
]

export const AAC_WORKING_GROUP_SECRETARIAT = AAC_WORKING_GROUP.filter(
  (m) => m.cohort === "secretariat"
)
export const AAC_WORKING_GROUP_MEMBERS = AAC_WORKING_GROUP.filter((m) => m.cohort === "members")
export const AAC_WORKING_GROUP_OBSERVERS = AAC_WORKING_GROUP.filter((m) => m.cohort === "observers")
