/** Generated by scripts/generate-brand-assets.mjs — do not edit by hand. */
export const BRAND_LOGO_PATH = "/brand/impact-hub-nairobi-logo.png"
export const BRAND_LOGO_SVG_PATH = "/brand/impact-hub-nairobi-logo.svg"
export const BRAND_MARK_PATH = "/brand/impact-hub-mark.png"
export const BRAND_MARK_SVG_PATH = "/brand/impact-hub-mark.svg"
export const BRAND_APP_ICON_SVG_PATH = "/brand/impact-hub-app-icon.svg"

/** Full horizontal logo dimensions (source PNG). */
export const BRAND_LOGO_WIDTH = 1000
export const BRAND_LOGO_HEIGHT = 413

/** Square tile width in the full logo (left mark). */
export const BRAND_LOGO_TILE_SIZE = 413

export const BRAND_LOGO_ASPECT_RATIO = 1000 / 413
export const BRAND_LOGO_TILE_RATIO = 413 / 1000
